spring.application.name=caching-demo-app

spring.datasource.url=jdbc:postgresql://localhost:5432/caching_demo_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
